stages: 
  - test
  - docs

language: python

jobs:
  include:
    - stage: test
      sudo: required
      python:
        - "2.7"
        - "3.6"
      services:
        - docker
      before_install:
        - docker pull vault:latest
        - docker ps -a
      install: pip install tox-travis
      script: tox

    - stage: docs
      python: "3.6"
      local-dir: ansible-repo/ansible/docs/docsite
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      install: 
        - mkdir ansible-repo && cd ansible-repo
        - git clone https://github.com/ansible/ansible.git 
        - git checkout v2.7.6
        - pip install -r ansible/docs/docsite/requirements.txt
        - pip install git+https://github.com/TerryHowe/ansible-modules-hashivault/
      script: cd ansible/docs/docsite/ && make webdocs .
      on:
        branch: ansible-webdocs
