---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: arrange - policies - functional_testing_policy_one
      hashivault_policy_set:
        name: functional_testing_policy_one
        rules: 'path "secret/*" {capabilities = ["read", "list"]}'

    - name: arrange - policies - functional_testing_policy_two
      hashivault_policy_set:
        name: functional_testing_policy_two
        rules: 'path "secret/*" {capabilities = ["read", "list"]}'

    - name: add idenity group
      hashivault_identity_group:
        name: test
        state: absent

    - name: remove identity group
      hashivault_identity_group:
        name: test
        state: present
      register: success_config

    - assert: { that: "{{ success_config.changed }} == True" }

    - name: chg metadata
      hashivault_identity_group:
        name: test
        state: present
        metadata:
          functional: testing
      register: chg_metadata

    - assert: { that: "{{ chg_metadata.changed }} == True" }

    - name: duplicate metadata
      hashivault_identity_group:
        name: test
        state: present
        metadata:
          functional: testing
      register: chg_metadata

    - assert: { that: "{{ chg_metadata.changed }} == False" }

    - name: chg policies - add functional_testing_policy_one
      hashivault_identity_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == True" }

    - name: duplicate policies
      hashivault_identity_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == False" }

    - name: chg policies - add functional_testing_policy_two
      hashivault_identity_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
          - functional_testing_policy_two
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == True" }

    - name: chg policies - remove functional_testing_policy_one
      hashivault_identity_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_two
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == True" }